#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy-pihole-docker
- name: Install docker & docker-compose
  package:
    name: 
     - docker.io 
     - docker-compose-v2
    state: latest 

- name: Make a directory for the containers data 
  file:
    path: '{{ docker_container_directory }}/pihole'
    state: directory
    recurse: true

- name: Create directories on {{ inventory_hostname }} 
  file:
    path: '{{ docker_compose_directory }}/pihole'
    state: directory
    recurse: true
    
- name: Copy over compose template, modifying as needed 
  template:
    src: pihole-compose.yml.j2
    dest: '{{ docker_compose_directory }}/pihole/docker-compose.yml'

- name: Create container with the compose file
  community.docker.docker_compose_v2:
    project_src: '{{ docker_compose_directory }}'
    state: present
    
