- name: Removing 10-uname 
  file:
    path: /etc/update-motd.d/10-uname
    state: absent
  notify:
    - restart_sshd

- name: Implement MOTD Template File
  template:
    src: motd.j2
    dest: /etc/motd
  notify:
    - restart_sshd