#SPDX-License-Identifier: MIT-0
---
- name: Creating {{ docker_container_config_directory }} directory
  file: 
    path: '{{ docker_container_config_directory }}/{{ item.name }}'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0755'
  loop: "{{ syncthing }}"

- name: Creating {{ docker_container_data_directory }} directory
  file: 
    path: '{{ docker_container_data_directory }}/{{ syncthing_directory }}'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0755'

# tasks file for docker-syncthing
- name: Creating container
  docker_container:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    state: '{{ item.state }}'
    published_ports: '{{ item.published_ports }}'
    env: '{{ item.env }}'
    pull: '{{ item.pull }}'
    volumes:
    - '{{ docker_container_config_directory }}/{{ item.name }}:/config'
    - '{{ syncthing_directory }}:/{{ syncthing_repo }}'
    - '{{ syncthing_directory2 }}:/{{ syncthing_repo2 }}'
    restart_policy: '{{ item.restart_policy }}'
  loop: "{{ syncthing }}"
