#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-syncthing
- name: Creating container
  docker_container:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    state: '{{ item.state }}'
    published_ports: '{{ item.published_ports }}'
    volumes: '{{ item.volume }}'
    env: '{{ item.env }}'
    pull: '{{ item.pull }}'
    restart_policy: '{{ item.restart_policy }}'
  loop: "{{ syncthing }}"
