#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy-pihole-docker
- name: Install docker 
  package:
    name: 
     - docker.io 
    state: latest 

- name: Creating on {{ inventory_hostname }}
  block:
    - name: Create directories on {{ inventory_hostname }} 
      file: 
        path: '{{ docker_container_directory }}/{{ item.name }}/'
        state: directory
        recurse: true
      loop: "{{ nginx }}"

    - name: Copying nginx.conf template 
      template:
        src: nginx.conf.j2
        dest: '{{ docker_container_directory }}/nginx/nginx.conf'

    - name: Creating containers {{ inventory_hostname }}..
      docker_container:
        name: '{{ item.name }}'
        image: '{{ item.image }}'
        state: '{{ item.state }}'
        recreate: '{{ item.recreate }}'
        published_ports: '{{ item.published_ports }}'
        volumes: '{{ item.volume }}'
      loop: "{{ nginx }}"
  when: install_nginx == 'true'