---
# Install initial packages
- name: Install packages
  hosts: homelab 
  become: true
  roles:
  - system-install-packages

## Configure local user account
- name: Configure local users
  hosts: homelab 
  vars_files:
   - vault/vault
  become: true
  roles:
  - system-users

## General homelab config on hosts
- name: Configure UFW 
  hosts: homelab
  become: true
  roles:
  - system-ufw

- name: Configure motd 
  hosts: homelab 
  become: true
  roles:
  - system-motd

## NFS Configurations
- name: Configure NFS server exports
  hosts: nfs_server 
  become: true
  roles:
  - storage-server-nfs

- name: Configure homelab wide NFS client mounts
  hosts: homelab
  become: true
  roles:
  - system-mount-nfs

## Configure specific services
- name: Configure pihole container
  hosts: docker 
  vars_files:
   - vault/vault
  become: true
  roles:
  - docker-pihole
  
- name: Configure nginx fileserver
  hosts: docker 
  become: true
  roles:
  - docker-nginx-fileserver

- name: Configure syncthing 
  hosts: docker 
  become: true
  roles:
  - docker-syncthing

## Configure Dockarr (This stuff is gitignore'd and safe to remove)
- name: Configure dockarr NFS client mounts
  hosts: dockarr 
  become: true
  roles:
  - storage-mount-nfs

- name: Configure Dockarr 
  hosts: dockarr 
  become: true
  roles:
  - dockarr
