---
################################
## NFS Server 
################################
- name: Configure NFS server exports
  hosts: nfs_server 
  become: true
  roles:
  - storage-server-nfs
  tags:
  -  nfs-server
  
################################
## Homelab Setup
################################
- name: Configure homelab host tasks
  hosts: homelab 
  vars_files:
   - vault/vault
  become: true
  roles:
  - system-users
  - system-motd
  - system-install-packages
  - system-ufw
  - storage-mount-nfs
  tags:
  -  system

################################
## Docker 
################################
- name: Configure Docker host containers 
  hosts: docker 
  become: true
  vars_files:
   - vault/vault
  roles:
  - docker-nginx-fileserver
  - docker-syncthing
  - docker-uptime-kuma
  - docker-pihole
  tags:
  -  docker

################################
## Minecraft 
################################
- name: Deploy Minecraft container
  hosts: minecraft 
  become: true
  roles:
  - docker-minecraft
  tags:
  -  minecraft 

################################
## Dockarr 
################################
- name: Configure dockarr NFS client mounts
  hosts: dockarr 
  become: true
  roles:
  - storage-mount-nfs
  - dockarr
  tags:
  -  dockarr