# Setting host level settings
- name: Set Timezone To '{{ timezone }}'
  timezone:
    name: '{{ timezone }}'

- name: Implement Chrony Template File
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
  notify:
    - restart_chronyd

# I noticed (atleast in 9.0.6) that setting the OS's timezone did not update the timezone in the UI
# This section will use the API to set the timezone
- name: Authenticate to Proxmox API
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_username }}"
      password: "{{ pve_password }}"
    validate_certs: false
  register: auth_response

- name: Set Auth Tokens
  set_fact:
    pve_ticket: "{{ auth_response.json.data.ticket }}"
    pve_csrf: "{{ auth_response.json.data.CSRFPreventionToken }}"

- name: Create Timezone
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/nodes/{{ ansible_hostname }}/time"
    method: PUT
    headers:
      Cookie: "PVEAuthCookie={{ pve_ticket }}"
      CSRFPreventionToken: "{{ pve_csrf }}"
    body_format: form-urlencoded
    body:
      timezone: "{{ timezone }}"
    validate_certs: false
  ignore_errors: true