#SPDX-License-Identifier: MIT-0
---
# tasks file for nfs
## Authentication
- name: Authenticate to Proxmox API
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_username }}"
      password: "{{ pve_password }}"
    validate_certs: false
  register: auth_response

- name: Set auth tokens
  set_fact:
    pve_ticket: "{{ auth_response.json.data.ticket }}"
    pve_csrf: "{{ auth_response.json.data.CSRFPreventionToken }}"

## Role Tasks
- name: Create NFS storages
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/storage"
    method: POST
    headers:
      Cookie: "PVEAuthCookie={{ pve_ticket }}"
      CSRFPreventionToken: "{{ pve_csrf }}"
    body_format: form-urlencoded
    body:
      storage: "{{ item.nfs_storage }}"
      type: "nfs"
      server: "{{ item.nfs_ip }}"
      export: "{{ item.nfs_path }}"
      content: "{{ item.nfs_content }}"
    validate_certs: false
  loop: "{{ nfs_servers }}"
  register: create_nfs_results
  ignore_errors: true

- name: 
  set_fact:
    pve_response: "{{ create_nfs_results.results | map(attribute='msg') | list }}"
    success_status: "{{ create_nfs_results.results | map(attribute='failed') | list }}"

- name: Show result message
  debug:
    var: pve_response
