#SPDX-License-Identifier: MIT-0
---
# tasks file for proxmox-host-setup
## Packages & Upgrades
- name: Install custom packages
  package:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ packages }}"

- name: Switch ProxMox to free repository
  block:
    - name: Removing the license-only repository on {{ inventory_hostname }}
      apt_repository:
        repo: '{{ pve_enterprise_repo }}'
        state: absent
        update_cache: false

    - name: Removing the license-only Ceph repository on {{ inventory_hostname }}
      apt_repository:
        repo: '{{ ceph_enterprise_repo }}'
        state: absent
        update_cache: false

    - name: Adding the ProxMox free repository
      apt_repository:
        repo: '{{ pve_nosub_repo }}'
        state: present
        update_cache: false

    - name: Adding the Ceph free repository
      apt_repository:
        repo: '{{ ceph_nosub_repo }}'
        state: present
        update_cache: false
  when: free_repo_mode == 'true'

- name: Upgrade and reboot ProxMox
  block:
    - name: Upgrade ProxMox to latest version
      apt:
        upgrade: dist
        update_cache: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_check

    - name: If a reboot is required, reboot the host after 30 seconds to apply the packages
      reboot:
        msg: 'Ansible initiated reboot is triggering in 30 seconds..'
        pre_reboot_delay: '{{ pre_reboot_delay }}'
      when: reboot_required_check.stat.exists
  when: upgrade_proxmox == 'true'

- name: Setting system block & NTP server
  block:
    - name: Set timezone to '{{ timezone }}'
      timezone:
        name: '{{ timezone }}'

    - name: Implement chrony template file
      template:
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
      notify:
        - restart_chronyd
  when: set_clock == 'true'

- name: Setting login banner
  block:
    - name: Removing 10-uname to prevent kernel logging info from appearing in the MOTD
      file:
        path: /etc/update-motd.d/10-uname
        state: absent
      notify:
        - restart_sshd

    - name: Implement motd template file
      template:
        src: ../templates/motd.j2
        dest: /etc/motd
      notify:
        - restart_sshd
  when: set_motd == 'true'

# Template was NOT used here as there is other host specific stuff in this file, that is unique to each setup
# This is probably an area for future improvement
- name: Configure NFS storage
  block:
    - name: Adding NFS storage {{ nfs_storage }} on {{ inventory_hostname }}
      blockinfile:
        path: /etc/pve/storage.cfg
        block: |
          nfs: {{ nfs_storage }}
                   export {{ nfs_path }}
                   path /mnt/pve/{{ nfs_storage }}
                   server {{ nfs_ip }}
                   content {{ nfs_content }}
                   prune-backups keep-all=1
  when: configure_nfs == 'true'