#SPDX-License-Identifier: MIT-0
---
# tasks file for motd

- name: Removing 10-uname to prevent kernel logging info from appearing in the MOTD
  file:
    path: /etc/update-motd.d/10-uname
    state: absent
  notify:
    - restart_sshd

- name: Implement motd template file
  template:
    src: motd.j2
    dest: /etc/motd
  notify:
    - restart_sshd