#SPDX-License-Identifier: MIT-0
---
# handlers file for proxmox-host-setup
- name: restart_sshd
  service:
    name: sshd
    state: restarted
- name: restart_chronyd
  service:
    name: chronyd
    state: restarted