#SPDX-License-Identifier: MIT-0
---
# tasks file for motd

- name: Set the login banner in sshd 
  lineinfile:
    path: /etc/ssh/sshd_config 
    regexp: "^#Banner"
    line: Banner /etc/motd 
  notify:
    - restart_sshd

- name: Implement motd template file
  template:
    src: ../templates/motd.j2
    dest: /etc/motd
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0755'
  notify:
    - restart_sshd