- name: Authenticate to Proxmox API
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_username }}"
      password: "{{ pve_password }}"
    validate_certs: false
  register: auth_response

- name: Set Auth Tokens
  set_fact:
    pve_ticket: "{{ auth_response.json.data.ticket }}"
    pve_csrf: "{{ auth_response.json.data.CSRFPreventionToken }}"

- name: Configure DNS Servers Using PUT
  uri:
    url: "https://{{ inventory_hostname }}:8006/api2/json/nodes/{{ ansible_hostname }}/dns"
    method: PUT
    headers:
      Cookie: "PVEAuthCookie={{ pve_ticket }}"
      CSRFPreventionToken: "{{ pve_csrf }}"
    body_format: form-urlencoded
    body:
      search: "{{ dns_searchdomain }}"
      dns1: "{{ dns1 }}"
      dns2: "{{ dns2 }}"
    validate_certs: false
  register: create_dns_results
  ignore_errors: true
