---
- name: ProxMox Host Configuration
  hosts: proxmox
  become: true
  vars_files:
   - vault/vault
  roles:
  - proxmox-motd
  - proxmox-time
  - proxmox-nfs
  - proxmox-dns
  - proxmox-single-host-update
  - proxmox-install-packages 

