#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-pihole
- name: Creating directories
  file: 
    path: '{{ docker_container_config_directory }}/{{ item.name }}'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0750'
  loop: "{{ pihole }}"

- name: Pull docker image prior to DNS config
  community.docker.docker_image:
    name: "{{ item.image }}"
    source: pull
  loop: "{{ pihole }}"

- name: Stop systemd-resolved to prevent port 53 conflict
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: false

- name: Deploy Pi-hole container(s)
  community.docker.docker_container:
    name: "{{ item.name }}"
    hostname: '{{ item.name }}'
    image: "{{ item.image }}"
    state: "{{ item.state }}"
    published_ports: "{{ item.published_ports }}"
    volumes: "{{ item.volumes }}"
    env: "{{ item.env }}"
    capabilities: "{{ item.capabilities }}"
    volumes:
      - "{{ docker_container_config_directory }}/{{ item.name }}/:/etc/pihole"
    restart_policy: '{{ item.restart_policy }}'
  loop: "{{ pihole }}"


