#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-nginx
- name: Creating directories
  file: 
    path: '{{ docker_container_data_directory }}/{{ item.name }}/'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0755'
  loop: "{{ pihole }}"

- name: Deploy Pi-hole container(s)
  community.docker.docker_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: "{{ item.state }}"
    published_ports: "{{ item.published_ports }}"
    volumes: "{{ item.volumes }}"
    env: "{{ item.env }}"
    capabilities: "{{ item.capabilities }}"
    pull: "{{ item.pull }}"
  loop: "{{ pihole }}"


