#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-nginx
- name: Creating directories
  file: 
    path: '{{ docker_container_data_directory }}/nginx-ansible/files/{{ item.name }}/'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0750'
  loop: "{{ nginx_file_directories }}"

- name: Copying nginx.conf template 
  template: 
    src: nginx.conf.j2
    dest: '{{ docker_container_data_directory }}/{{ item.name }}/nginx.conf'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0750'
  loop: "{{ nginx }}"

- name: Creating container
  docker_container:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    state: '{{ item.state }}'
    published_ports: '{{ item.published_ports }}'
    volumes: '{{ item.volume }}'
    restart_policy: '{{ item.restart_policy }}'
  loop: "{{ nginx }}"
