#SPDX-License-Identifier: MIT-0
---
# tasks file for docker-nginx
- name: Creating {{ docker_container_config_directory }} directory
  file: 
    path: '{{ docker_container_config_directory }}/{{ item.name }}'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0640'
  loop: "{{ nginx }}"

- name: Copying nginx.conf template 
  template: 
    src: nginx.conf.j2
    dest: '{{ docker_container_config_directory }}/{{ item.name }}/nginx.conf'
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0750'
  loop: "{{ nginx }}"

- name: Creating {{ nginx_repo_directory }} directory
  file: 
    path: '{{ nginx_repo_directory }}'
    state: directory
    recurse: true
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0755'

- name: Creating nginx container
  docker_container:
    name: '{{ item.name }}'
    image: '{{ item.image }}'
    state: '{{ item.state }}'
    published_ports: '{{ item.published_ports }}'
    volumes:
      - "{{ docker_container_config_directory }}/{{ item.name }}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{ nginx_repo_directory }}:/usr/share/nginx/html:ro"
    restart_policy: '{{ item.restart_policy }}'
  loop: "{{ nginx }}"
