#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy-pihole-docker
- name: Install docker & docker-compose
  package:
    name: 
     - docker.io 
     - docker-compose-v2
    state: latest 

- name: Make a directory for the docker compose file
  file:
    path: '{{ compose_directory }}'
    state: directory
    recurse: true

- name: Make a directory for the containers data 
  file:
    path: '{{ container_data_directory }}'
    state: directory
    recurse: true

- name: Copy over compose template, modifying as needed 
  template:
    src: pihole-compose.yml.j2
    dest: '{{ compose_directory }}docker-compose.yml'

- name: Create container with the compose file
  community.docker.docker_compose_v2:
    project_src: '{{ compose_directory }}'
    state: present