#SPDX-License-Identifier: MIT-0
---
# tasks file for proxmox-nosub-repo

- name: Disabling the repository 
  apt_repository:
    repo: '{{ item.repo }}'
    state: absent
    update_cache: false
  loop: "{{ disable_repository }}"

- name: Enable the repository 
  apt_repository:
    repo: '{{ item.repo }}'
    state: present
    update_cache: false
  loop: "{{ enable_repository }}"

